- name: create user password
  hosts: prod
  become: true
  vars_files:
      - user-inforation.yml
  tasks:
      - name: create user password
        vars:
           password: "{{ lookup('password', './password-{{item.name}}'  ' length=6') }}"
        user:
           name: "{{ item.name }}"
           uid: "{{ item.uid }}"
           comment: "{{ item.first | capitalize }} {{ item.middle | capitalize }} {{ item.last | capitalize }}"
           password: "{{ password | password_hash('sha512')}}"
           update_password: on_create
        with_items:
           - "{{ myusers }}"


